### ISSUE TITLE
authOnlyIfLoggedInPatterns redirects to the login URL

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-cas-client#2]
The user is flagged as 'logged in' when the auth cookie is present, regardless of actual login status.

If the app is not actually logged in, e.g. login occurs on another tab or server restart, all authOnlyIfLoggedInPatterns redirect to the login URL. This includes ajax calls that end up failing.

Changes to correctly identify the login status are on the branch https://github.com/AtlasOfLivingAustralia/ala-cas-client/tree/2.3.1 and are for use with https://github.com/AtlasOfLivingAustralia/spatial-portal

**Comment by sbearcsiro** [comment]
@adam-collins This version should be 2.2.1 as it doesn't include 2.3 changes.
